language: python

dist: trusty

git:
  submodules: false

env:
  - QGIS_REPO=http://qgis.org/debian-nightly
  - QGIS_REPO=http://qgis.org/debian-nightly-release

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7d967d9679efbbc43466
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - sudo apt-get -qq -y update

install:
  - sudo add-apt-repository -y ${QGIS_REPO}
  - sudo apt-get update
  - sudo apt-get install -y --force-yes qgis python-qgis xvfb
  - pip install -r requirements.txt

before_script:
  - export PATH=/usr/bin:$PATH # escape the virtual env

script:
  - flake8
  - nose2

after_success:
  - scripts/ci/make_release.sh
